[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "automation-bit"
version = "0.1.0"


[dependencies]
panic-halt = "~0.2"
microbit="0.7.0"
embedded-hal = "0.2.3"
cortex-m-rt="0.6.8"
nrf51-hal = "0.6.2"
nb = "0.1.2"

